### ISSUE TITLE
Erreur à la commande /bos

### ISSUE THREAD

**Issue by misric** [CubesOfLegend/BallsOfSteel#12]
visiblement y'a un soucis depuis la mise à jour, on ne peut plus faire de commandes /bos

http://pastebin.com/psKNYjzW

**Comment by aturcey** [comment]
C'est bien l'erreur que j'ai eu un moment, corrigé avec cette version : MinigamesLib-1.14.12-20160918.123727-3  [Télechargement direct](http://nexus.xworlds.eu/nexus/content/repositories/mce-snapshots/com/github/MCE-Plugins/MinigamesLib/1.14.12-SNAPSHOT/MinigamesLib-1.14.12-20160918.123727-3.jar)

**Comment by misric** [comment]
erreur corrigée !
